### PR TITLE
Produce the jar for databricks using maven.

### PR DESCRIPTION
**Pull request by OPeyrusse**
In this PR, I rewrite the maven definition of the project in order to be able to produce a jar compatible with JRE8.
To do so, you can run the command `./mvnw -P databricks clean package`. It will produce a jar _spark-lib-version.jar_ containing the conditions and the aggregations (I reused your readme to get what to include).
This jar can be created while using the JDK 16 or lower.

I haven't tested it yet on Databricks but I check that the java version of the compiled classes was correct.

This new project definition has now two distinct profiles: 
 - one named "standalone" that depends on _spark-sql_, that you can use to run tests locally
 - one named "databricks", to produce the version for databricks.

The profile "databricks" also depends optionally on _spark-sql_, in order to easily produce the jar. Because the version of _spark-sql_ in the POM is aligned with the server, I am confident that the API on which your classes depends on is correct. That is enough because a jar file is like a dynamic library.
Tell me if this optional dependency is conflicting with the library you have included manually. If so, I can review the config to add yet another profile to optionally load this dependency.

### CODE REVIEW

**Comment by OPeyrusse** [comment]
To enable a maven profile in Intellij, follow this guide https://www.jetbrains.com/help/idea/work-with-maven-profiles.html#declare_maven_profiles

**Comment by arnaudframmery** [comment]
I can build the jar thanks to the maven command, but there is issues with java version when I launch tests or benchmarks with the databricks profile (it tries to run with java 8 instead of java 16).
It can be fixed by changing these lines : 
```
<configuration>
  <source>${java.version}</source>
  <target>1.8</target> ==> <target>16</target>
  <release>16</release> ==> <release>16</release>
  <includes>
    <include>io/atoti/spark/condition/**/*.java</include>
    <include>io/atoti/spark/aggregation/**/*.java</include>
  </includes>
</configuration>
```
But it will obviously break the jar building ...
 Anyway even with this change there is a conflict between local spark and databricks one :(

**Comment by arnaudframmery** [comment]
For the conflict between local spark (aka maven one) and databricks one, why not link the jars in ...\anaconda3\envs\databricks\Lib\site-packages\pyspark\jars\* into the pom.xml file and not using the depency given by maven ?

**Comment by arnaudframmery** [comment]
In fact it seems very difficult to add a folder of jars with maven dependency mechanics. Creating another profile seems to be a better option as you said

**Comment by OPeyrusse** [comment]
> In fact it seems very difficult to add a folder of jars with maven dependency mechanics. Creating another profile seems to be a better option as you said

Exactly what I was writing. I though about doing so, using Maven _system_ dependencies. Unfortunately, this requires to setup every dependency one by one. Looking at the _jars_ folders, I saw too many jars.
I looked for ways to define a whole portion of the class path manually, but that's not how maven works :disappointed: 
That's why I went to this option in the end.
I will add the second profile, not to pollute IDEs already configured with the dependencies.

**Comment by arnaudframmery** [comment]
I archieve to make it work with some modifications : 
for example if I am on the databricks profile, I run `./mvnw -P databricks clean package clean`.
Then I build the project and I can run tests and benchmarks on the cluster

**Comment by OPeyrusse** [comment]
Looks good to me. I understand that the databrick profile is designed for the IDE configured with databricks jar.
And "jar-creation" builds the jar.
Since I agree with your last version, I will merge this PR.

**Pull request merged**
